name: Build and publish DB artifact

on: workflow_dispatch
#  push:
#    branches: 
#      - main

jobs:

  # Job to build and publish the dacpac
  Build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      - uses: actions/checkout@v3.3.0

      # Build dacpac using dotnet build
      - name: Build Database project
        run: |
          dotnet build

      # Publish artifact
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: sqldb
          path: ${{ github.workspace }}/bin/Debug/ 
